dist: trusty
sudo: required
language: node_js
node_js:
- '10'
- '8'
os:
- linux
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
before_script:
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run lint
- npm run test-once
- npm run e2e
deploy:
  provider: firebase
  token:
    secure: pXWK2w3MqG/dsrFuD8Pi96giTq2wHUvU/phvihHKTymIef59ZQLTy01thnq9uXlTr9gzdMLrzPAZ02I9EkB0QNKOBkYmUcmMC7GwwFbASTLUUSKUFNzJVHsnuXTK6Z3UwEwU/5zquJG9JUlc6ELUKKcE18mjimpsDpp0b9Zmn27XlNR7tcOakMtc4L3YwoUfGjRx7X5/CndJ+VbX80OXtX7rTAySPHITAGQ0ef2X4KX/DKwWIiUacMjNLit6GsZ0JsRkKt7QkKmpIT6DIk5yGrpCRgtfx1pRxljBIZZDf4+2Ov1z8ywrovwIfh37oVsU/tXuTL1HmneVKFso4/5qADyjm+h7s0PTeKud/PQzAGeKRSkBbibj2LaXD8d3R3TlFom71aj1gJR324HduB6stfy57C3V9wg89S6Dqutt3SZlPbyDU9KtJNaBJ1nrfawTmsEqXgWVGyoNOM+ri2W9FyfWRgkClpMmlXlCRB2qWeVHgDzpWeFNLV+2pczNIdKd5Vg2ttbI0RNOQbqjYN3cb21NPAToXSkkBqsUKnF8oFfpsEKmuHmOvX9K9BBwnI78krOnXdgTJQtfRCZ6EBN2Teo5d92RzVgxTPle2oXkMJAWbkjHgruBsYjFy+94+rINeEStnCrfD6BiXwa10tPLs2Mat0hWqSf/NqSh2Ym4L1E=
  message: "Automatic deploy from travis"
