name: Deploy

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint && npm run lint:scss

      - name: Build
        run: npm run build:prod

      - name: Deploy to Firebase
        if: success()
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
